[project]
name = "learningrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "timm>=1.0.19",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
