from global_vars import LOSSPATH
from os import path
import torch
import pandas as pd
import numpy as np

class LossCollector:
    show_digits = 5

    def __init__(self):
        # values generated by model inference
        self.itemnames: list[str] = [
            "probability_predictions", # always keep as first arg
            "policy_gradients", 
            "value_predictions", 
            "value_labels", 
            "Pi_loss", "V_loss", "entropy_loss"
            ]
        self.game_ids: list[np.ndarray] = []
        self.loss_items_indices: list[int] = []
        self.items: list[list[torch.Tensor]] = []
        for index, itemname in enumerate(self.itemnames):
            self.items.append([])
            if "loss" in itemname:
                self.loss_items_indices.append(index)
        
    def index(self, item_name: str):
        return self.itemnames.index(item_name)
        

    def last_loss(self)->str:
        result = ""
        for lii in self.loss_items_indices:
            number_in_str = f"{self.items[lii][-1].item():.{self.show_digits}g}"
            result+=f"{self.itemnames[lii]}: {number_in_str:<{self.show_digits+7}}"
        return result
    
    def append(self, game_id: np.ndarray, *args: torch.Tensor):
        self.game_ids.append(game_id)
        if len(args)!=len(self.itemnames):
            raise Warning(f"Appending incomplete information {len(args)}/{len(self.itemnames)}, requires {', '.join(self.itemnames)}")
        [item.append(arg.detach()) for item, arg in zip(self.items,args)]

    def empty(self):
        self.items = [[] for _ in self.itemnames]
        self.game_ids = []

    def to_df(self) -> pd.DataFrame:
        # concat items into numpy arrays
        items = [torch.stack(item).cpu().numpy() for item in self.items]

        # expected shape (print_period, parallel_games, replay_buffer_length, n_symmetries )
        # using value labels for expected shape
        target_shape = items[self.index("value_predictions")].shape
        target_shape = (target_shape[0], target_shape[1], target_shape[2]-1, target_shape[3])

        # removing probability predictions because it has last dimension of 9
        probability_predictions = items.pop(self.index("probability_predictions"))[:,:,:-1]

        items.append(np.expand_dims(np.stack(self.game_ids),-1))
        item_names = [*self.itemnames[1:], "game_id"]
        expanded_arrays = []
        for item in items:
            shape = item.shape
            if len(shape) == 1:
                item = item.reshape(shape[0], 1, 1, 1)
                shape = item.shape
            elif len(shape) == 3:
                item = item.reshape(shape[0], shape[1], shape[2], 1)
                shape = item.shape
            if shape[2] > target_shape[2]:
                item = item[:, :, :-1]
            item = np.broadcast_to(item, target_shape)
            expanded_arrays.append(item)
        
        df = pd.DataFrame(probability_predictions.reshape(-1,9))

        for name, item in zip(item_names, expanded_arrays):
            df[name] = item.flatten()
        
        return df
    
    def write_csv(self) -> None:
        location = LOSSPATH
        df = self.to_df()
        if path.isfile(location): # file already exists
            df.to_csv(location, mode='a', index=False, header = False)
        else: # file doesn't exists
            df.to_csv(location, mode='w', index=False, header = True)