from global_vars import LOSSPATH
from os import path
import torch
import pandas as pd
import numpy as np

class LossCollector:
    show_digits = 5

    def __init__(self):
        # values fed into the model
        self.inputnames: list[str] = [ # when concatenated
            "state", # (n_parallel x replay_length, n_symmetries, 9) -> (n_batches, n_parallel x replay_length, n_symmetries, 9)
            "actions", # (n_parallel, replay_length, n_symmetries) -> (n_batches, n_parallel, replay_length, n_symmetries)
            "turn", # (n_parallel, replay_length) -> (n_batches, n_parallel, replay_length)
            "rewards", # (n_parallel, replay_length) -> (n_batches, n_parallel, replay_length)
            "game_id", # (n_parallel, replay_length) -> (n_batches, n_parallel, replay_length)
        ]

        # values generated by model inference and label values
        self.outputnames: list[str] = [
            "probability_predictions", # (n_parallel, replay_length, n_symmetries, 9) -> (n_batches, n_parallel, replay_length, n_symmetries, 9)
            "policy_gradients", # (n_parallel, replay_length-1) 
            "value_predictions", # (n_parallel, replay_length, n_symmetries)
            "value_labels", # (n_parallel, replay_length - 1)
            ]

        # scalar loss values
        self.lossnames: list[str] = [
            "Pi_loss", 
            "V_loss", 
            "entropy_loss",
        ]
        self.empty()

        self.wrapped = [("inputs", self.inputnames, self.inputitems), ("outputs", self.outputnames, self.outputitems), ("loss", self.lossnames, self.lossitems)]


    def last_loss(self)->str:
        result = ""
        for name, item in zip(self.lossnames, self.lossitems):
            number_in_str = f"{item[-1].item():.{self.show_digits}g}"
            result+=f"{name}: {number_in_str:<{self.show_digits+7}}"
        return result
    
    def append(self, inputs: list[np.ndarray], outputs: list[torch.Tensor], loss: list[torch.Tensor]):
        for (id_str, names, items), args in zip(self.wrapped, [inputs, outputs, loss]):
            if len(args) != len(names):
                raise Exception(f"argument {id_str} is of wrong length, requires: {names}")
            items.append(args)
        self.n_batches+=1

    def empty(self):
        self.n_batches = 0
        self.inputitems: list[list[np.ndarray]] = [[] for _ in self.inputnames]
        self.outputitems: list[list[torch.Tensor]] = [[] for _ in self.outputnames]
        self.lossitems: list[list[torch.Tensor]] = [[] for _ in self.lossnames]

    # def to_df(self) -> pd.DataFrame:
    #     # concat items into numpy arrays
    #     inputs = [np.stack(items) for items in self.inputitems]
    #     outputs = [torch.stack(items).cpu().numpy() for items in self.outputitems]
    #     loss = [torch.stack(items).cpu().numpy() for items in self.lossitems]

    #     # expected shape (print_period, parallel_games, replay_buffer_length, n_symmetries )
    #     # using value labels for expected shape
    #     target_shape = items[self.index("value_predictions")].shape
    #     target_shape = (target_shape[0], target_shape[1], target_shape[2]-1, target_shape[3])

    #     # removing probability predictions because it has last dimension of 9
    #     probability_predictions = items.pop(self.index("probability_predictions"))[:,:,:-1]

    #     items.append(np.expand_dims(np.stack(self.game_ids),-1))
    #     item_names = [*self.itemnames[1:], "game_id"]
    #     expanded_arrays = []
    #     for item in items:
    #         shape = item.shape
    #         if len(shape) == 1:
    #             item = item.reshape(shape[0], 1, 1, 1)
    #             shape = item.shape
    #         elif len(shape) == 3:
    #             item = item.reshape(shape[0], shape[1], shape[2], 1)
    #             shape = item.shape
    #         if shape[2] > target_shape[2]:
    #             item = item[:, :, :-1]
    #         item = np.broadcast_to(item, target_shape)
    #         expanded_arrays.append(item)
        
    #     df = pd.DataFrame(probability_predictions.reshape(-1,9))

    #     for name, item in zip(item_names, expanded_arrays):
    #         df[name] = item.flatten()
        
    #     return df
    
    # def write_csv(self) -> None:
    #     location = LOSSPATH
    #     df = self.to_df()
    #     if path.isfile(location): # file already exists
    #         df.to_csv(location, mode='a', index=False, header = False)
    #     else: # file doesn't exists
    #         df.to_csv(location, mode='w', index=False, header = True)